// Generated by gencpp from file nao_control/WalkResponse.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_MESSAGE_WALKRESPONSE_H
#define NAO_CONTROL_MESSAGE_WALKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_control
{
template <class ContainerAllocator>
struct WalkResponse_
{
  typedef WalkResponse_<ContainerAllocator> Type;

  WalkResponse_()
    : result()  {
    }
  WalkResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::nao_control::WalkResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_control::WalkResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WalkResponse_

typedef ::nao_control::WalkResponse_<std::allocator<void> > WalkResponse;

typedef boost::shared_ptr< ::nao_control::WalkResponse > WalkResponsePtr;
typedef boost::shared_ptr< ::nao_control::WalkResponse const> WalkResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_control::WalkResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_control::WalkResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nao_control::WalkResponse_<ContainerAllocator1> & lhs, const ::nao_control::WalkResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nao_control::WalkResponse_<ContainerAllocator1> & lhs, const ::nao_control::WalkResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nao_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nao_control::WalkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_control::WalkResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control::WalkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control::WalkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control::WalkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control::WalkResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_control::WalkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::nao_control::WalkResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_control::WalkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_control/WalkResponse";
  }

  static const char* value(const ::nao_control::WalkResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_control::WalkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::nao_control::WalkResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_control::WalkResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WalkResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_control::WalkResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_control::WalkResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_CONTROL_MESSAGE_WALKRESPONSE_H
