// Generated by gencpp from file nao_control/Walk.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_MESSAGE_WALK_H
#define NAO_CONTROL_MESSAGE_WALK_H

#include <ros/service_traits.h>


#include <nao_control/WalkRequest.h>
#include <nao_control/WalkResponse.h>


namespace nao_control
{

struct Walk
{

typedef WalkRequest Request;
typedef WalkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Walk
} // namespace nao_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_control::Walk > {
  static const char* value()
  {
    return "5c2b345790c4d9484fcc900040c864dc";
  }

  static const char* value(const ::nao_control::Walk&) { return value(); }
};

template<>
struct DataType< ::nao_control::Walk > {
  static const char* value()
  {
    return "nao_control/Walk";
  }

  static const char* value(const ::nao_control::Walk&) { return value(); }
};


// service_traits::MD5Sum< ::nao_control::WalkRequest> should match
// service_traits::MD5Sum< ::nao_control::Walk >
template<>
struct MD5Sum< ::nao_control::WalkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control::Walk >::value();
  }
  static const char* value(const ::nao_control::WalkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control::WalkRequest> should match
// service_traits::DataType< ::nao_control::Walk >
template<>
struct DataType< ::nao_control::WalkRequest>
{
  static const char* value()
  {
    return DataType< ::nao_control::Walk >::value();
  }
  static const char* value(const ::nao_control::WalkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_control::WalkResponse> should match
// service_traits::MD5Sum< ::nao_control::Walk >
template<>
struct MD5Sum< ::nao_control::WalkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_control::Walk >::value();
  }
  static const char* value(const ::nao_control::WalkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_control::WalkResponse> should match
// service_traits::DataType< ::nao_control::Walk >
template<>
struct DataType< ::nao_control::WalkResponse>
{
  static const char* value()
  {
    return DataType< ::nao_control::Walk >::value();
  }
  static const char* value(const ::nao_control::WalkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_CONTROL_MESSAGE_WALK_H
