// Generated by gencpp from file nao_control/Order.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_MESSAGE_ORDER_H
#define NAO_CONTROL_MESSAGE_ORDER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_control
{
template <class ContainerAllocator>
struct Order_
{
  typedef Order_<ContainerAllocator> Type;

  Order_()
    : ord()  {
    }
  Order_(const ContainerAllocator& _alloc)
    : ord(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ord_type;
  _ord_type ord;





  typedef boost::shared_ptr< ::nao_control::Order_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_control::Order_<ContainerAllocator> const> ConstPtr;

}; // struct Order_

typedef ::nao_control::Order_<std::allocator<void> > Order;

typedef boost::shared_ptr< ::nao_control::Order > OrderPtr;
typedef boost::shared_ptr< ::nao_control::Order const> OrderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_control::Order_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_control::Order_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nao_control::Order_<ContainerAllocator1> & lhs, const ::nao_control::Order_<ContainerAllocator2> & rhs)
{
  return lhs.ord == rhs.ord;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nao_control::Order_<ContainerAllocator1> & lhs, const ::nao_control::Order_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nao_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nao_control::Order_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_control::Order_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control::Order_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control::Order_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control::Order_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control::Order_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_control::Order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ebdd50f63bd077f07b93a25172b98b2";
  }

  static const char* value(const ::nao_control::Order_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ebdd50f63bd077fULL;
  static const uint64_t static_value2 = 0x07b93a25172b98b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_control::Order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_control/Order";
  }

  static const char* value(const ::nao_control::Order_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_control::Order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ord\n"
"\n"
;
  }

  static const char* value(const ::nao_control::Order_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_control::Order_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ord);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Order_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_control::Order_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_control::Order_<ContainerAllocator>& v)
  {
    s << indent << "ord: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ord);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_CONTROL_MESSAGE_ORDER_H
