// Generated by gencpp from file nao_control/WalkRequest.msg
// DO NOT EDIT!


#ifndef NAO_CONTROL_MESSAGE_WALKREQUEST_H
#define NAO_CONTROL_MESSAGE_WALKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_control
{
template <class ContainerAllocator>
struct WalkRequest_
{
  typedef WalkRequest_<ContainerAllocator> Type;

  WalkRequest_()
    : joint()  {
    }
  WalkRequest_(const ContainerAllocator& _alloc)
    : joint(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _joint_type;
  _joint_type joint;





  typedef boost::shared_ptr< ::nao_control::WalkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_control::WalkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WalkRequest_

typedef ::nao_control::WalkRequest_<std::allocator<void> > WalkRequest;

typedef boost::shared_ptr< ::nao_control::WalkRequest > WalkRequestPtr;
typedef boost::shared_ptr< ::nao_control::WalkRequest const> WalkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_control::WalkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_control::WalkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nao_control::WalkRequest_<ContainerAllocator1> & lhs, const ::nao_control::WalkRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nao_control::WalkRequest_<ContainerAllocator1> & lhs, const ::nao_control::WalkRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nao_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nao_control::WalkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_control::WalkRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control::WalkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_control::WalkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control::WalkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_control::WalkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_control::WalkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23b081b5cb543c8335b9afac2f3e238c";
  }

  static const char* value(const ::nao_control::WalkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23b081b5cb543c83ULL;
  static const uint64_t static_value2 = 0x35b9afac2f3e238cULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_control::WalkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_control/WalkRequest";
  }

  static const char* value(const ::nao_control::WalkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_control::WalkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string joint \n"
;
  }

  static const char* value(const ::nao_control::WalkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_control::WalkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WalkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_control::WalkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_control::WalkRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_CONTROL_MESSAGE_WALKREQUEST_H
