# Copyright 2019 RTDP Team2. All rights reserved. GNU General Public License v3.0.
# This is a basic workflow to check the license lines.

name: Check License Lines
on:
  push:
    branches: [main]
jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check License Lines
      uses: kt3k/license_checker@v1.0.6
